"""
Application Constants
"""

# User Roles
ROLE_MANAGER = "Manager"
ROLE_TECHNICIAN = "Technician"

ROLES = {
    ROLE_MANAGER: "Manager",
    ROLE_TECHNICIAN: "Technician",
}

# Worksheet Status
WORKSHEET_STATUS_OPEN = "Open"
WORKSHEET_STATUS_WAITING = "Waiting for Parts"
WORKSHEET_STATUS_CLOSED = "Closed"

WORKSHEET_STATUSES = [
    WORKSHEET_STATUS_OPEN,
    WORKSHEET_STATUS_WAITING,
    WORKSHEET_STATUS_CLOSED,
]

# Stock Transaction Types
TRANSACTION_TYPE_RECEIVED = "received"
TRANSACTION_TYPE_ISSUED = "issued"
TRANSACTION_TYPE_ADJUSTMENT = "adjustment"
TRANSACTION_TYPE_INITIAL_STOCK = "initial_stock"

TRANSACTION_TYPES = [
    TRANSACTION_TYPE_RECEIVED,
    TRANSACTION_TYPE_ISSUED,
    TRANSACTION_TYPE_ADJUSTMENT,
    TRANSACTION_TYPE_INITIAL_STOCK,
]

# Asset Action Types
ACTION_CREATED = "created"
ACTION_MODIFIED = "modified"
ACTION_DELETED = "deleted"
ACTION_MANUAL_UPDATED = "manual_updated"

ASSET_ACTIONS = [ACTION_CREATED, ACTION_MODIFIED, ACTION_DELETED, ACTION_MANUAL_UPDATED]

# PM Task Status
PM_STATUS_COMPLETED = "completed"
PM_STATUS_SKIPPED = "skipped"
PM_STATUS_PENDING = "pending"

# Machine Status (ISO 55001)
MACHINE_STATUS_ACTIVE = "Aktív"
MACHINE_STATUS_STOPPED = "Stopped"
MACHINE_STATUS_SCRAPPED = "Selejtezve"

# Audit Log Actions
AUDIT_LOGIN = "login"
AUDIT_LOGOUT = "logout"
AUDIT_CREATE = "create"
AUDIT_UPDATE = "update"
AUDIT_DELETE = "delete"

# Color Scheme (Material Design 3)
COLOR_PRIMARY = "#2962FF"
COLOR_PRIMARY_LIGHT = "#42A5F5"
COLOR_PRIMARY_DARK = "#1565C0"
COLOR_SECONDARY = "#455A64"
COLOR_SUCCESS = "#4CAF50"
COLOR_WARNING = "#FF9800"
COLOR_ERROR = "#F44336"
COLOR_INFO = "#2196F3"
COLOR_BACKGROUND = "#FAFAFA"
COLOR_SURFACE = "#FFFFFF"

# Font Sizes
FONT_SIZE_TITLE = 28
FONT_SIZE_SUBTITLE = 20
FONT_SIZE_HEADING = 16
FONT_SIZE_BODY = 14
FONT_SIZE_LABEL = 12
FONT_SIZE_SMALL = 10

# Spacing
SPACING_SMALL = 8
SPACING_MEDIUM = 16
SPACING_LARGE = 24
SPACING_EXTRA_LARGE = 32
