"""Add scrapping documents and system logs

Revision ID: 8523b6b9fda5
Revises: cc7308902ed0
Create Date: 2025-12-14 03:09:22.473302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8523b6b9fda5'
down_revision: Union[str, Sequence[str], None] = 'cc7308902ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create system_logs table
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_category', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Add foreign key separately for SQLite compatibility
    try:
        op.create_foreign_key('fk_system_logs_user_id', 'system_logs', 'users', ['user_id'], ['id'])
    except:
        pass  # SQLite may not support foreign keys
    op.create_index('idx_system_logs_category', 'system_logs', ['log_category'], unique=False)
    op.create_index('idx_system_logs_date', 'system_logs', ['year', 'month', 'week', 'day'], unique=False)
    op.create_index('idx_system_logs_entity', 'system_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_system_logs_timestamp', 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_day'), 'system_logs', ['day'], unique=False)
    op.create_index(op.f('ix_system_logs_log_category'), 'system_logs', ['log_category'], unique=False)
    op.create_index(op.f('ix_system_logs_month'), 'system_logs', ['month'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_week'), 'system_logs', ['week'], unique=False)
    op.create_index(op.f('ix_system_logs_year'), 'system_logs', ['year'], unique=False)
    # Create scrapping_documents table
    op.create_table('scrapping_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('docx_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('worksheet_id', sa.Integer(), nullable=True),
    sa.Column('pm_history_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Add foreign keys separately for SQLite compatibility
    try:
        op.create_foreign_key('fk_scrapping_documents_user_id', 'scrapping_documents', 'users', ['generated_by_user_id'], ['id'])
        op.create_foreign_key('fk_scrapping_documents_worksheet_id', 'scrapping_documents', 'worksheets', ['worksheet_id'], ['id'])
        op.create_foreign_key('fk_scrapping_documents_pm_history_id', 'scrapping_documents', 'pm_histories', ['pm_history_id'], ['id'])
    except:
        pass  # SQLite may not support foreign keys
    op.create_index('idx_scrapping_entity', 'scrapping_documents', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_scrapping_timestamp', 'scrapping_documents', ['generated_at'], unique=False)
    
    # Note: Other detected changes (constraints, foreign keys) are skipped for SQLite compatibility
    # They should be handled in the model definitions or separate migrations
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_request_pdfs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('pm_worksheet_pdfs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_pm_tasks_next_due_date'), table_name='pm_tasks')
    op.drop_constraint(None, 'pm_histories', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_constraint(None, 'machines', type_='unique')
    op.drop_index('idx_scrapping_timestamp', table_name='scrapping_documents')
    op.drop_index('idx_scrapping_entity', table_name='scrapping_documents')
    op.drop_table('scrapping_documents')
    op.drop_index(op.f('ix_system_logs_year'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_week'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_month'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_log_category'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_day'), table_name='system_logs')
    op.drop_index('idx_system_logs_timestamp', table_name='system_logs')
    op.drop_index('idx_system_logs_entity', table_name='system_logs')
    op.drop_index('idx_system_logs_date', table_name='system_logs')
    op.drop_index('idx_system_logs_category', table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
