"""add_work_request_and_pm_worksheet_pdfs

Revision ID: c6d436d3133d
Revises: 12954ba29005
Create Date: 2025-12-13 18:07:08.470448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d436d3133d'
down_revision: Union[str, Sequence[str], None] = '12954ba29005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # worksheet_id column already added manually, just create the new tables
    
    # Create work_request_pdfs table (if not exists)
    try:
        op.create_table('work_request_pdfs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('pm_task_id', sa.Integer(), nullable=False),
            sa.Column('pdf_path', sa.String(length=500), nullable=False),
            sa.Column('generated_at', sa.DateTime(), nullable=True),
            sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
            sa.Column('page_count', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['pm_task_id'], ['pm_tasks.id'], ),
            sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('pm_task_id')
        )
    except:
        pass
    
    # Create pm_worksheet_pdfs table (if not exists)
    try:
        op.create_table('pm_worksheet_pdfs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('pm_history_id', sa.Integer(), nullable=False),
            sa.Column('pdf_path', sa.String(length=500), nullable=False),
            sa.Column('generated_at', sa.DateTime(), nullable=True),
            sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
            sa.Column('page_count', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['pm_history_id'], ['pm_histories.id'], ),
            sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('pm_history_id')
        )
    except:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pm_worksheet_pdfs')
    op.drop_table('work_request_pdfs')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_index(op.f('ix_pm_tasks_next_due_date'), table_name='pm_tasks')
    op.drop_constraint(None, 'pm_histories', type_='foreignkey')
    op.drop_column('pm_histories', 'worksheet_id')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_constraint(None, 'machines', type_='unique')
    # ### end Alembic commands ###
