"""add_vacation_and_shift_management

Revision ID: de9c675ae5a3
Revises: 8523b6b9fda5
Create Date: 2025-12-14 16:10:38.566094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9c675ae5a3'
down_revision: Union[str, Sequence[str], None] = '8523b6b9fda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shift_schedules_effective', 'shift_schedules', ['effective_from', 'effective_to'], unique=False)
    op.create_index('idx_shift_schedules_user_id', 'shift_schedules', ['user_id'], unique=False)
    op.create_table('vacation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('vacation_type', sa.String(length=50), nullable=True, server_default='annual'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, server_default='pending'),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('days_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vacation_requests_dates', 'vacation_requests', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_vacation_requests_requested_at', 'vacation_requests', ['requested_at'], unique=False)
    op.create_index('idx_vacation_requests_status', 'vacation_requests', ['status'], unique=False)
    op.create_index('idx_vacation_requests_user_id', 'vacation_requests', ['user_id'], unique=False)
    op.create_table('vacation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacation_request_id', sa.Integer(), nullable=False),
    sa.Column('docx_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacation_request_id'], ['vacation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vacation_documents_generated_at', 'vacation_documents', ['generated_at'], unique=False)
    op.create_index('idx_vacation_documents_request_id', 'vacation_documents', ['vacation_request_id'], unique=False)
    # Note: SQLite doesn't support ALTER TABLE for constraints, skipping asset_tag unique constraint
    # op.create_unique_constraint(None, 'machines', ['asset_tag'])
    op.create_foreign_key(None, 'machines', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'machines', 'users', ['created_by_user_id'], ['id'])
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_foreign_key(None, 'pm_histories', 'worksheets', ['worksheet_id'], ['id'])
    op.create_index(op.f('ix_pm_tasks_next_due_date'), 'pm_tasks', ['next_due_date'], unique=False)
    op.alter_column('pm_worksheet_pdfs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'scrapping_documents', 'users', ['generated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'scrapping_documents', 'worksheets', ['worksheet_id'], ['id'])
    op.create_foreign_key(None, 'scrapping_documents', 'pm_histories', ['pm_history_id'], ['id'])
    op.create_foreign_key(None, 'system_logs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('vacation_days_per_year', sa.Integer(), nullable=True, server_default='20'))
    op.add_column('users', sa.Column('vacation_days_used', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('shift_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('shift_start_time', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('shift_end_time', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('work_days_per_week', sa.Integer(), nullable=True, server_default='5'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['anonymized_by_user_id'], ['id'])
    op.alter_column('work_request_pdfs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_request_pdfs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('users', 'work_days_per_week')
    op.drop_column('users', 'shift_end_time')
    op.drop_column('users', 'shift_start_time')
    op.drop_column('users', 'shift_type')
    op.drop_column('users', 'vacation_days_used')
    op.drop_column('users', 'vacation_days_per_year')
    op.drop_constraint(None, 'system_logs', type_='foreignkey')
    op.drop_constraint(None, 'scrapping_documents', type_='foreignkey')
    op.drop_constraint(None, 'scrapping_documents', type_='foreignkey')
    op.drop_constraint(None, 'scrapping_documents', type_='foreignkey')
    op.alter_column('pm_worksheet_pdfs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_pm_tasks_next_due_date'), table_name='pm_tasks')
    op.drop_constraint(None, 'pm_histories', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    # Note: SQLite doesn't support ALTER TABLE for constraints
    # op.drop_constraint(None, 'machines', type_='unique')
    op.drop_index('idx_vacation_documents_request_id', table_name='vacation_documents')
    op.drop_index('idx_vacation_documents_generated_at', table_name='vacation_documents')
    op.drop_table('vacation_documents')
    op.drop_index('idx_vacation_requests_user_id', table_name='vacation_requests')
    op.drop_index('idx_vacation_requests_status', table_name='vacation_requests')
    op.drop_index('idx_vacation_requests_requested_at', table_name='vacation_requests')
    op.drop_index('idx_vacation_requests_dates', table_name='vacation_requests')
    op.drop_table('vacation_requests')
    op.drop_index('idx_shift_schedules_user_id', table_name='shift_schedules')
    op.drop_index('idx_shift_schedules_effective', table_name='shift_schedules')
    op.drop_table('shift_schedules')
    # ### end Alembic commands ###
