"""
Script to create default scrapping document template
"""

import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from config.app_config import TEMPLATES_DIR
from services.settings_service import set_selected_scrapping_template
from database.session_manager import SessionLocal


def create_default_scrapping_template():
    """
    Creates a default DOCX template for scrapping documents.
    """
    template_path = TEMPLATES_DIR / "default_scrapping_template.docx"
    
    document = Document()
    
    # Set page margins
    section = document.sections[0]
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)
    
    # Title
    title = document.add_heading('Selejtezési Lap / Scrapping Document', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add spacing
    document.add_paragraph()
    
    # Information table
    table = document.add_table(rows=1, cols=2)
    table.style = 'Light Grid Accent 1'
    
    # Entity type
    row = table.rows[0]
    row.cells[0].text = "Típus / Type:"
    row.cells[1].text = "${entity.type}"
    
    # Entity name
    row = table.add_row()
    row.cells[0].text = "Név / Name:"
    row.cells[1].text = "${entity.name}"
    
    # Entity identifier (SKU or Serial Number)
    row = table.add_row()
    row.cells[0].text = "Azonosító / Identifier:"
    row.cells[1].text = "${entity.sku}${entity.serial_number}"
    
    # Reason
    row = table.add_row()
    row.cells[0].text = "Selejtezés oka / Reason:"
    row.cells[1].text = "${reason}"
    
    # Scrapped by
    row = table.add_row()
    row.cells[0].text = "Selejtezte / Scrapped by:"
    row.cells[1].text = "${scrapped_by}"
    
    # Scrapped at
    row = table.add_row()
    row.cells[0].text = "Selejtezés dátuma / Scrapped at:"
    row.cells[1].text = "${scrapped_at}"
    
    # Worksheet info (if applicable)
    row = table.add_row()
    row.cells[0].text = "Munkalap ID / Worksheet ID:"
    row.cells[1].text = "${worksheet.id}"
    
    row = table.add_row()
    row.cells[0].text = "Munkalap címe / Worksheet Title:"
    row.cells[1].text = "${worksheet.title}"
    
    # PM task info (if applicable)
    row = table.add_row()
    row.cells[0].text = "PM feladat neve / PM Task Name:"
    row.cells[1].text = "${pm_task.name}"
    
    # Generated at
    row = table.add_row()
    row.cells[0].text = "Generálva / Generated at:"
    row.cells[1].text = "${generated_at}"
    
    # Add spacing
    document.add_paragraph()
    
    # Notes section
    document.add_heading('Megjegyzések / Notes', level=1)
    notes_para = document.add_paragraph("Ez a dokumentum automatikusan generálva lett a rendszer által.")
    notes_para.add_run("\nThis document was automatically generated by the system.")
    
    # Save template
    template_path.parent.mkdir(parents=True, exist_ok=True)
    document.save(template_path)
    print(f"✓ Default scrapping template created: {template_path}")
    
    # Set this template as the default in settings
    session = SessionLocal()
    try:
        set_selected_scrapping_template(template_path, session)
        session.commit()
        print(f"Default scrapping template set to: {template_path}")
    except Exception as e:
        session.rollback()
        print(f"Error setting default scrapping template: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    create_default_scrapping_template()

