"""
Script to create default storage transfer document template
"""

import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from config.app_config import TEMPLATES_DIR
from services.settings_service import set_selected_storage_transfer_template
from database.session_manager import SessionLocal


def create_default_storage_transfer_template():
    """
    Creates a default DOCX template for storage transfer documents.
    """
    template_path = TEMPLATES_DIR / "default_storage_transfer_template.docx"
    
    document = Document()
    
    # Set page margins
    section = document.sections[0]
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)
    
    # Title
    title = document.add_heading('Áttárolási Lap / Storage Transfer Document', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add spacing
    document.add_paragraph()
    
    # Information table
    table = document.add_table(rows=1, cols=2)
    table.style = 'Light Grid Accent 1'
    
    # Part name
    row = table.rows[0]
    row.cells[0].text = "Alkatrész neve / Part Name:"
    row.cells[1].text = "{PART_NAME}"
    
    # Part SKU
    row = table.add_row()
    row.cells[0].text = "Cikkszám (SKU) / Part SKU:"
    row.cells[1].text = "{PART_SKU}"
    
    # Quantity
    row = table.add_row()
    row.cells[0].text = "Mennyiség / Quantity:"
    row.cells[1].text = "{QUANTITY}"
    
    # Source location
    row = table.add_row()
    row.cells[0].text = "Forrás tárhely neve / Source Location Name:"
    row.cells[1].text = "{SOURCE_LOCATION_NAME}"
    
    row = table.add_row()
    row.cells[0].text = "Forrás tárhely útvonala / Source Location Path:"
    row.cells[1].text = "{SOURCE_LOCATION_PATH}"
    
    row = table.add_row()
    row.cells[0].text = "Forrás tárhely kódja / Source Location Code:"
    row.cells[1].text = "{SOURCE_LOCATION_CODE}"
    
    # Target location
    row = table.add_row()
    row.cells[0].text = "Cél tárhely neve / Target Location Name:"
    row.cells[1].text = "{TARGET_LOCATION_NAME}"
    
    row = table.add_row()
    row.cells[0].text = "Cél tárhely útvonala / Target Location Path:"
    row.cells[1].text = "{TARGET_LOCATION_PATH}"
    
    row = table.add_row()
    row.cells[0].text = "Cél tárhely kódja / Target Location Code:"
    row.cells[1].text = "{TARGET_LOCATION_CODE}"
    
    # Transfer date
    row = table.add_row()
    row.cells[0].text = "Áttárolás dátuma / Transfer Date:"
    row.cells[1].text = "{TRANSFER_DATE}"
    
    # Notes
    row = table.add_row()
    row.cells[0].text = "Megjegyzés / Notes:"
    row.cells[1].text = "{NOTES}"
    
    # Generated at
    row = table.add_row()
    row.cells[0].text = "Generálva / Generated at:"
    row.cells[1].text = "{CURRENT_DATE}"
    
    # Add spacing
    document.add_paragraph()
    
    # Notes section
    document.add_heading('További megjegyzések / Additional Notes', level=1)
    notes_para = document.add_paragraph("Ez a dokumentum automatikusan generálva lett a rendszer által.")
    notes_para.add_run("\nThis document was automatically generated by the system.")
    
    # Save template
    template_path.parent.mkdir(parents=True, exist_ok=True)
    document.save(template_path)
    print(f"[OK] Default storage transfer template created: {template_path}")
    
    # Set this template as the default in settings
    session = SessionLocal()
    try:
        set_selected_storage_transfer_template(template_path, session)
        session.commit()
        print(f"Default storage transfer template set to: {template_path}")
    except Exception as e:
        session.rollback()
        print(f"Error setting default storage transfer template: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    create_default_storage_transfer_template()

